sudo: false
language: node_js
node_js:
- 0.12.2
script:
- npm test
before_install:
- npm install -g npm@2.7.6
- npm -v
- npm config set loglevel http
- export HOME=`pwd`
- mkdir -p $HOME/tmp
- npm config set tmp $HOME/tmp
- mkdir -p .git
- git config --global credential.helper "store --file=$HOME/.git/credentials"
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- git config --global push.default simple
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.git/credentials
- git remote set-url origin https://github.com/AdaptiveMe/generator-adaptiveme.git
- |-
  if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git checkout master
  fi
- export CURRENT_TAG=`git describe --abbrev=0`
after_success: |-
  if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    export PACKAGE_TAG=`node bin/version.js`
    echo Github:$CURRENT_TAG Package:$PACKAGE_TAG
    if [ "$CURRENT_TAG" == "$PACKAGE_TAG" ]; then
      echo "Bump package version."
      npm version patch
      git push origin
    elif [ "$CURRENT_TAG" != "$PACKAGE_TAG" ]; then
      echo "Tag package version."
      git tag -a "$PACKAGE_TAG" -m "Release $PACKAGE_TAG"
      git push origin --tags
    fi
  fi
deploy:
  provider: npm
  email: carlos@adaptive.me
  api_key:
    secure: eK/ISezqpkeqjHh45F/syIlh357RlbE95MT5PapGmrUDPU8H71VYSoIhy7if63I8scyWm9jDt71erexf4lM3cqo57eHc7U/8TxTBvTmJyEckK6e9qLNTump7uKma56KPrtpTOkL73sMz1NJlDFpBfF+I0EKXqqj6bkxs+tVS5/A=
  on:
    tags: true
    repo: AdaptiveMe/generator-adaptiveme
env:
  global:
    secure: ScgIsLlESsEgDWBcdnrXOfyZ8vvbfkegz3WG69DJsNHKUg9dC/aQ8zkrI6u8sLbSWYEzagLOjfFSsNndXRmIMPBFi30m4zVuZl7FgJ0d9dTcFwf0ol7wL0/uwulTrS2/ieHDXyz6kKg295kGVX7ixkziroOVfggKSOX8ZpIBRJY=
