sudo: true
language: node_js
node_js:
- '0.12'
script:
- npm test
before_install:
- export HOME=`pwd`
- mkdir -p .git
- git config --global credential.helper "store --file=$HOME/.git/credentials"
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- git config --global push.default simple
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.git/credentials
- |-
  git remote set-url origin https://github.com/AdaptiveMe/generator-adaptiveme.git
  if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git checkout master
  fi

- export CURRENT_TAG=`git describe --abbrev=0`

after_success: |-
  if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    export PACKAGE_TAG=`node bin/version.js`
    echo Github:$CURRENT_TAG Package:$PACKAGE_TAG
    if [ "$CURRENT_TAG" == "$PACKAGE_TAG" ]; then
      echo "Commit bumped file version."
      grunt bump:patch
    elif [ "$CURRENT_TAG" != "$PACKAGE_TAG" ]; then
      echo "Tag current file version."
      git tag -a "$PACKAGE_TAG" -m "Release $PACKAGE_TAG"
      git push origin --tags
    fi
  fi
  if [ "$TRAVIS_TAG" ]; then
    echo "Directory List:"
    ls -lart
    echo "Size of directories and files:"
    du -smc * | sort -n
    echo "Size of filesystem:"
    df -k
    echo "Removing node_modules:"
    rm -rf node_modules
  fi
deploy:
  provider: npm
  email: carlos@adaptive.me
  api_key:
    secure: SagzAI364KBH0seGaqiQjnY22IbrBTLzCz0UPyRLo0qzLlYJ2OiQOqrEPwFKNz/+s1/ErtzVykf66zWukNst4RAUj6s2L2iAuFwgakFyLgHUYYS3CtHZoDo5Ihu3l39InOnW6vEQk0oHjIJTb0anu2RHDhD0GBeP9lVXFV8wdoQ=
  on:
    tags: true
    repo: AdaptiveMe/generator-adaptiveme
env:
  global:
    secure: ScgIsLlESsEgDWBcdnrXOfyZ8vvbfkegz3WG69DJsNHKUg9dC/aQ8zkrI6u8sLbSWYEzagLOjfFSsNndXRmIMPBFi30m4zVuZl7FgJ0d9dTcFwf0ol7wL0/uwulTrS2/ieHDXyz6kKg295kGVX7ixkziroOVfggKSOX8ZpIBRJY=
