sudo: false
language: node_js
node_js:
- "4.1"

script:
- npm test

deploy:
  provider: npm
  email: "carlos@adaptive.me"
  api_key:
    secure: PW6kLnvPEPfJhgGx6jwSuho7JbC8i/BpyiTD1RPOy3Z9wPY8h8RsA+5cTXyNt2toAoBAs2DMIOnNe6KhpF0b9Ffk3xRpyYYHSiziD+KuX/3O796nc9/xVPkCpg+g4A+ewlgBiqOMb7XbgZbg0WZQFjEqJljsDc48hbCSa5rg35w=
  on:
    tags: true
